apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: s3-bucket-terraform
  title: S3 Bucket with Terraform
  description: Create an S3 bucket using Terraform
spec:
  owner: user:guest
  type: service
  parameters:
  - title: Configure S3 Bucket
    required:
    - s3name
    - acl
    properties:
      s3name:
        title: S3 Bucket Name
        type: string
        description: Unique name of the S3 bucket
        ui:autofocus: true
        ui:options:
          rows: 5
      acl:
        title: Access Control List
        type: string
        description: Access control level for the S3 bucket
        default: private
        enum:
          - private
          - public-read
          - public-read-write
        enumNames:
          - Private
          - Public Read
          - Public Read/Write
        ui:options:
          rows: 5

  steps:
  - id: github-action
    name: Trigger Terraform Deployment
    action: github:actions:dispatch
    input:
      workflowId: terraform-deploy.yml
      repoUrl: 'github.com?repo=infrastructure&owner=aparasxidis'
      branchOrTagName: "main"
      workflowInputs:
        s3name: ${{ parameters.s3name }}
        acl: ${{ parameters.acl }}